# This file contains tasks to setup a cronjob for setting up Dynamic DNS with Route53, which will
# create a record consisting of your public domain and the public ip provided to you by your ISP.
# Depending on the `minute` setting, it will update the record every few minutes.
#
# Assumes the `setup-aws-env.yml` tasks have been run and the AWS credentials are available in the environment.
---
- name: Create IAM policy for Route53 DNS-01 challenges and DDNS updates
  amazon.aws.iam_managed_policy:
    access_key: "{{ aws_access_key_id }}"
    secret_key: "{{ aws_secret_access_key }}"
    policy_name: route53-ddns-policy
    policy_description: "Policy for Route53 DNS-01 challenges and DDNS updates"
    policy: "{{ lookup('template', 'templates/route53-policy.json.j2') }}"
    state: present
  register: route53_iam_policy

- name: Attach policy to user
  amazon.aws.iam_user:
    access_key: "{{ aws_access_key_id }}"
    secret_key: "{{ aws_secret_access_key }}"
    name: "{{ aws_iam_user }}"
    managed_policies:
      - "{{ route53_iam_policy.policy.arn }}"
    state: present

- name: Copy Route53 DDNS update script
  template:
    src: route53-ddns.sh.j2
    dest: /usr/local/bin/update_route53_ddns.sh
    mode: '0755'

- name: Ensure MAILTO is set for cron notifications
  cron:
    name: "MAILTO"
    env: yes
    job: "{{ email }}"
    user: root
  when: email is defined and email != ""

- name: Create cron job for Route53 DDNS updates
  cron:
    name: "Update Route 53 DDNS"
    job: "/usr/local/bin/update_route53_ddns.sh"
    user: "{{ ansible_user }}"
    minute: "*/5" #Update every 5 minutes

- name: Install logrotate config for Route53 DDNS log
  ansible.builtin.copy:
    dest: /etc/logrotate.d/update_route53_ddns
    mode: '0644'
    content: |
      {{ cron_log_file }} {
          daily
          rotate 7
          compress
          missingok
          notifempty
          create 0640 root adm
          postrotate
              :
          endscript
      }


