# Includes tasks to setup the Lets-Encrypt CA using cert-manager
#
# It also ensures that Kubernetes CoreDNS will forward DNS queries to public DNS servers as opposed
# to the local resolvers on the node.
#
# We do this because if the node’s resolver points to an internal network DNS server (say, your router or an internal DNS forwarder),
# and that internal DNS server has wildcard overrides for your domain or routes outbound traffic in non-standard ways,
# it might resolve "acme-v02.api.letsencrypt.org" to the public ingress IP (or worse, intercept outbound HTTPS traffic altogether).
---

# Ensures that CoreDNS will forward DNS queries to public DNS servers
- name: Get current coredns configmap
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    namespace: kube-system
    name: coredns
  register: coredns_cm

- name: Check if Corefile uses /etc/resolv.conf
  ansible.builtin.set_fact:
    needs_corefile_update: "{{ 'forward . /etc/resolv.conf' in coredns_cm.resources[0].data.Corefile }}"

- name: Replace forward line in coredns Corefile if necessary
  ansible.builtin.set_fact:
    new_corefile: "{{ coredns_cm.resources[0].data.Corefile | regex_replace('forward \\.\\s+/etc/resolv\\.conf', 'forward . 1.1.1.1 8.8.8.8') }}"
  when: needs_corefile_update

- name: Apply updated coredns configmap if modified
  kubernetes.core.k8s:
    api_version: v1
    kind: ConfigMap
    namespace: kube-system
    name: coredns
    definition:
      metadata:
        name: coredns
        namespace: kube-system
      data:
        Corefile: "{{ new_corefile }}"
    state: present
  when: needs_corefile_update

- name: Restart coredns pods if configmap was updated
  kubernetes.core.k8s:
    api_version: v1
    kind: Pod
    namespace: kube-system
    label_selectors:
      - "k8s-app=kube-dns"
    state: absent
  when: needs_corefile_update

# Create the Lets-Encrypt CA
- name: Create Lets-Encrypt CA and Issuer
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/lets-encrypt-ca.yml.j2') }}"