# Default variables used by the ntp-server role.
---

# Location of the chrony service config file
chrony_conf_file: /etc/chrony/chrony.conf

# Defines the upstream NTP servers.
#
# A list of dictionaries with the following keys:
#
# server:  host or pool
# type:    (Optional) Defaults to server. Maps to a time source in the
#           configuration file. Can be one of server, peer, pool.
# options: (Optional) List of options that depends on type, see Chrony
#          documentation for details.
#
# See: https://chrony.tuxfamily.org/doc/4.0/chrony.conf.html
ntp_servers:
  - server: ntp.ubuntu.org
    type: pool
    options:
      - option: iburst
      - option: maxsources
        val: 4
  - server: 0.ubuntu.pool.ntp.org
    type: pool
    options:
      - option: iburst
      - option: maxsources
        val: 1
  - server: 1.ubuntu.pool.ntp.org
    type: pool
    options:
      - option: iburst
      - option: maxsources
        val: 1
  - server: 2.ubuntu.pool.ntp.org
    type: pool
    options:
      - option: iburst
      - option: maxsources
        val: 2

# Optionally specify a host, subnet, or network from which to allow NTP
# connections to the host acting as an NTP server.
ntp_allow_hosts: []
