# Automatic proxy injection: https://linkerd.io/2.12/features/proxy-injection/
---
# Make longhorn-manager container listen on localhost
- name: Change longhorn-manager POD_IP env variable
  ansible.builtin.command:
    cmd: "kubectl set env daemonset/longhorn-manager -n {{ k3s_longhorn_namespace }} POD_IP=0.0.0.0"
  register: change_pod_env
  changed_when: '"daemonset.apps/longhorn-manager env updated" in change_pod_env.stdout'

- name: Annotate Longhorn Manager
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: DaemonSet
      metadata:
        name: longhorn-manager
        namespace: "{{ k3s_longhorn_namespace }}"
      spec:
        template:
          metadata:
            annotations:
              linkerd.io/inject: enabled
    state: patched

- name: Annotate Longhorn Dashboard
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: longhorn-dashboard
        namespace: "{{ k3s_longhorn_namespace }}"
      spec:
        template:
          metadata:
            annotations:
              linkerd.io/inject: enabled
    state: patched

- name: Annotate public longhorn-dashboard
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: longhorn-dashboard
        namespace: "{{ k3s_longhorn_namespace }}"
      spec:
        template:
          metadata:
            annotations:
              linkerd.io/inject: enabled
    state: patched
  when: enable_public_longhorn_dashboard
