# Tasks for the installation of the kube-prometheus-stack (see https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#kube-prometheus-stack)
---
- name: Create the monitoring namespace
  kubernetes.core.k8s:
    name: "{{ k3s_monitoring_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create Grafana admin credentials secret
  kubernetes.core.k8s:
    state: present
    namespace: "{{ k3s_monitoring_namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: grafana-admin-creds
      type: Opaque
      stringData:
        admin-user: "{{ grafana_admin_user }}"
        admin-password: "{{ grafana_admin_passwd }}"

- name: Add Prometheus Community chart repo.
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Deploy kube-prometheus-stack Helm chart
  kubernetes.core.helm:
    name: kube-prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: "{{ k3s_monitoring_namespace }}"
    update_repo_cache: true
    state: present
    values: "{{ lookup('template', 'templates/prometheus-helm-values.yml.j2') | from_yaml }}"

- name: Wait for Pods to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ k3s_monitoring_namespace }}"
    wait: yes
    wait_sleep: 10
    wait_timeout: 360
    wait_condition:
      type: Ready
      status: "True"

# Expose Prometheus and Alertmanager dashboards with IngressRoute and BasicAuth
- ansible.builtin.set_fact:
    prometheus_basic_auth: "prometheus-basic-auth"
    alertmanager_basic_auth: "alertmanager-basic-auth"

- name: Create BasicAuth credentials for Prometheus dashboard
  include_role:
    name: traefik-basic-auth
  vars:
    basic_auth_namespace: "{{ k3s_monitoring_namespace }}"
    basic_auth_name: "{{ prometheus_basic_auth }}"
    basic_auth_user: "{{ prometheus_basic_auth_user }}"
    basic_auth_passwd: "{{ prometheus_basic_auth_passwd }}"

- name: Create BasicAuth credentials for Alertmanager dashboard
  include_role:
    name: traefik-basic-auth
  vars:
    basic_auth_namespace: "{{ k3s_monitoring_namespace }}"
    basic_auth_name: "{{ alertmanager_basic_auth }}"
    basic_auth_user: "{{ alertmanager_basic_auth_user }}"
    basic_auth_passwd: "{{ alertmanager_basic_auth_passwd }}"

- name: Configure IngressRoute to Prometheus Dashboard
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'templates/prometheus-dashboard.yml.j2') }}"
    state: present

- name: Configure IngressRoute to Alertmanager Dashboard
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'templates/alertmanager-dashboard.yml.j2') }}"
    state: present

- name: Configure IngressRoute to Grafana Dashboard
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'templates/grafana-dashboard.yml.j2') }}"
    state: present

- name: Configure IngressRoute to Public Grafana Dashboard
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'templates/grafana-dashboard-public.yml.j2') }}"
    state: present
  when: enable_public_traefik_dashboard