# Updates all software packages on the PIs
#
# Shamelessly copied from https://github.com/geerlingguy/deskpi-super6c-cluster/blob/master/upgrade.yml
---
- name: Update all software packages on the cluster.
  hosts: cluster
  become: true

  tasks:
    - name: Update all software.
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Check if a reboot is required.
      stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required

    - name: Reboot the server (if required).
      reboot:
      when: reboot_required.stat.exists == true

    - name: Remove dependencies that are no longer required.
      apt:
        autoremove: yes