# Handlers for the tasks in the Cluster Preparation role
---
- name: Reboot host
  ansible.builtin.reboot:
    msg: '{{ "Rebooting " + inventory_hostname|string + "..." }}'
    connect_timeout: 5
    reboot_timeout: 60
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami

- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
