# Default variables used by the MetalLB role
---
# Namespace for metalLB
k3s_metallb_namespace: metallb-system

# Range of IP addresses that MetalLB can use to assign IPs to services
# For example:
#  - 192.168.10.0/24
#  - 192.168.9.1-192.168.9.5
k3s_external_ip_range:
