# Tasks for preparing every host in the cluster for the installation of Longhorn.
#
# Note that these tasks will WIPE THE DISK!
# Be extra careful before executing these tasks and make sure that you have set the variables properly.
---
# Install prerequisite software and modules
- name: Install prerequisites
  include_tasks: ../../tasks/install_prereqs.yml

- name: Prepare the disk
  include_tasks: prepare_disk.yml
  when:
    - longhorn_prepare_disk | bool
    - (ansible_mounts | selectattr('mount', 'eq', longhorn_storage_path) | selectattr('fstype', 'eq', 'ext4') | list | length <= 0)
    - (ansible_mounts | selectattr('mount', 'eq', longhorn_storage_path) | selectattr('fstype', 'eq', 'xfs')  | list | length <= 0)

- name: Ensure storage path exists
  ansible.builtin.file:
    path: "{{ longhorn_storage_path }}"
    state: directory
    mode: '0777'
  when: not longhorn_prepare_disk | bool