# Tasks for preparing a disk for use by Longhorn
#
# These include
# - wiping the disk
# - formatting the disk to ext4
# - creating a mount point
#
# Note that these tasks will WIPE THE DISK!
# Be extra careful before executing these tasks and make sure that you have set the variables properly.
---
- name: Wipe the disk
  block:
    - debug:
        msg: Wiping {{ longhorn_disk_device }} on {{ inventory_hostname }}
    - ansible.builtin.command: wipefs -a /dev/{{ longhorn_disk_device }}

- name: Format the disk to the desired filesystem type
  community.general.filesystem:
    dev: "/dev/{{ longhorn_disk_device }}"
    fstype: "{{ longhorn_fstype }}"
    state: present

- name: Mount the disk
  ansible.posix.mount:
    src: "/dev/{{ longhorn_disk_device }}"
    path: "{{ longhorn_storage_path }}"
    fstype: "{{ longhorn_fstype }}"
    state: mounted







