# Default variables used by the cert-manager role
---
# Namespace for the Certificate Manager
k3s_cert_manager_namespace: cert-manager-system

# Enable the self-signed Certificate Issuer for the Private CA
enable_selfsigned: true
# Enable `Let's Encrypt` ACME (Automated Certificate Management Environment) provider for the Public CA
enable_letsencrypt: false
# Enable AWS' `Route 53` DNS provider for routing public traffic to the cluster ingress.
enable_route53: false

# Replace with your public domain
public_domain:

# Name of the certificate authority (CA) for self-signed certificates on the Local Network
private_ca: k3s-ca
# Name of the certificate authority (CA) for certificates on the Internet
public_ca: letsencrypt

# Issuer of TLS certificates on the Local Network (e.g. self-signed)
local_tls_issuer: "{{ private_ca }}-issuer"
# Issuer of TLS certificates on the Internet (e.g. 'Let's Encrypt')
public_tls_issuer: "{{ public_ca }}-issuer"

# Valid E-mail address for registration with `Let's Encrypt`
email:

# When using the Route 53 DNS provider, replace with your AWS Access Key ID and Secret Access Key.
# Consider using Ansible Vault to store these variables securely.
aws_access_key_id:
aws_secret_access_key:
aws_region: us-east-1

# When using the Route 53 DNS provider, replace with your AWS Hosted Zone ID.
aws_hosted_zone_id: