# Default variables used by the cert-manager role
---
# Namespace for the Certificate Manager
k3s_cert_manager_namespace: cert-manager-system

# Enable `Let's Encrypt` ACME provider
enable_letsencrypt: false

# Valid E-mail address for registration with `Let's Encrypt`
acme_email: