# Defines the common task of rebooting the Pis
---
- ansible.builtin.reboot:
    msg: '{{ "Rebooting " + inventory_hostname|string + "..." }}'
    connect_timeout: 5
    reboot_timeout: 120
    pre_reboot_delay: 0
    post_reboot_delay: 60
    test_command: whoami
