# Task to download the Linkerd CLI (see https://linkerd.io/2.12/getting-started/)
---
- name: Install Linkerd CLI
  ansible.builtin.get_url:
    url: "{{ linkerd_package_url }}"
    dest: "{{ linkerd_bin }}"
    owner: root
    group: root
    mode: '0755'