# This file contains tasks to generate a user:password pair.
#
# For use with Traefik's BasicAuth middleware declared in 'templates/basic_auth_middleware.yml'
---
- name: Ensure required packages are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - 'apache2-utils'
    - 'python3-passlib'

- name: Generate htpasswd entry for Traefik BasicAuth
  community.general.htpasswd:
    path: /tmp/traefik_htpasswd
    name: "{{ traefik_basic_auth_user }}"
    password: "{{ traefik_basic_auth_passwd }}"
    crypt_scheme: bcrypt
    state: present

- name: Read generated htpasswd entry
  ansible.builtin.slurp:
    src: /tmp/traefik_htpasswd
  register: htpasswd_content

- name: Set htpasswd string variable
  ansible.builtin.set_fact:
    traefik_auth_htpasswd_pair: "{{ htpasswd_content.content | b64decode | trim }}"

- name: Remove temporary htpasswd file
  ansible.builtin.file:
    path: /tmp/traefik_htpasswd
    state: absent
