# This file contains tasks to generate a user:password pair.
#
# For use with Traefik's BasicAuth middleware declared in 'templates/basic_auth_middleware.yml'
---
- name: Ensure `htpasswd` utility is installed.
  ansible.builtin.package:
    name: 'apache2-utils'
    state: present
  become: true

- name: Generate user:password pair.
  shell:
    cmd: >-
      htpasswd -nb {{ traefik_basic_auth_user }} {{ traefik_basic_auth_passwd }} | base64
  register: htpasswd
  changed_when: false

- name: Set user:password pair fact.
  set_fact:
    traefik_auth_htpasswd_pair: "{{ htpasswd.stdout }}"