# Tasks for the installation of Traefik (see https://github.com/traefik/traefik-helm-chart#installing)
---
- name: Create the namespace for Traefik
  kubernetes.core.k8s:
    name: "{{ k3s_traefik_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add Traefik chart repo.
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: "https://traefik.github.io/charts"

- name: Deploy Traefik Helm chart
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    release_namespace: "{{ k3s_traefik_namespace }}"
    update_repo_cache: true
    state: present
    values: "{{ lookup('template', 'templates/traefik-helm-values.yml.j2') | from_yaml }}"

- name: Wait for Pods to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ k3s_traefik_namespace }}"
    wait: yes
    wait_sleep: 10
    wait_timeout: 360
    wait_condition:
      type: Ready
      status: "True"

- ansible.builtin.set_fact:
    traefik_basic_auth: "traefik-basic-auth"

- name: Create BasicAuth credentials for the Traefik dashboard
  include_role:
    name: traefik-basic-auth
  vars:
    k3s_basic_auth_namespace: "{{ k3s_traefik_namespace }}"
    k3s_basic_auth_name: "{{ traefik_basic_auth }}"
    basic_auth_user: "{{ traefik_basic_auth_user }}"
    basic_auth_passwd: "{{ traefik_basic_auth_passwd }}"

- name: Configure Traefik Middleware and Dashboard
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'templates/' + item ) }}"
    state: present
  with_items:
    - http-redirect-middleware.yml.j2
    - traefik-dashboard.yml.j2

- name: Configure Traefik Public IngressRoute to Dashboard
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'templates/traefik-dashboard-public.yml.j2') }}"
    state: present
  when: enable_public_traefik_dashboard