---
- name: Remove cron job for Route53 DDNS updates
  cron:
    name: "Update Route 53 DDNS"
    state: absent

- name: Remove Route53 DDNS cron job script file
  ansible.builtin.file:
    path: /usr/local/bin/update_route53_ddns.sh
    state: absent

- name: Gather all Route53 records
  amazon.aws.route53_info:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    hosted_zone_id: "{{ aws_hosted_zone_id }}"
    query: record_sets
  register: route53_records

- name: Remove all non-SOA/NS records from Route53
  amazon.aws.route53:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    hosted_zone_id: "{{ aws_hosted_zone_id }}"
    record: "{{ item.name }}"
    type: "{{ item.type }}"
    value: "{{ item.records }}"
    ttl: "{{ item.ttl }}"
    state: absent
  loop: "{{ route53_records.resource_record_sets }}"
  when: item.type not in ['SOA', 'NS']

- name: Detach **all** managed policies from user
  amazon.aws.iam_user:
    access_key: "{{ aws_access_key_id }}"
    secret_key: "{{ aws_secret_access_key }}"
    name: "{{ aws_iam_user }}"
    managed_policies: []
    state: present

- name: Delete Route53 DDNS managed policy
  amazon.aws.iam_managed_policy:
    access_key: "{{ aws_access_key_id }}"
    secret_key: "{{ aws_secret_access_key }}"
    policy_name: route53-ddns-policy
    state: absent

- name: Remove AWS credentials from environment
  lineinfile:
    path: /etc/environment
    state: absent
    regexp: "{{ item }}"
  with_items:
    - "^AWS_ACCESS_KEY_ID=.*$"
    - "^AWS_SECRET_ACCESS_KEY=.*$"