# Default variables used by the opensearch-install role
---
k3s_opensearch_namespace: "opensearch"

# Last version to work with Raspberry Pi 4
opensearch_app_version: "2.9.0"
opensearch_chart_version: "2.34.0"

# From these variables Kubernetes will create resources named `opensearch-cluster-master`
opensearch_cluster_name: "opensearch-cluster"
opensearch_node_group: "master"

# Endpoint for the OpenSearch REST API on the local network
opensearch_rest_api: "api.opensearch.localnet"

# Custom OpenSearch Users
opensearch_logger_user: "logstash"
opensearch_monitoring_user: "monitor"
opensearch_dashboards_user: "kibanaro"

# Security credentials. Override with Ansible Vault variables.
opensearch_admin_passwd: "!s3cr3t"
opensearch_kibana_server_passwd: "!s3cr3t"
opensearch_snapshot_restore_passwd: "!s3cr3t"
opensearch_logger_passwd: "!s3cr3t"
opensearch_monitoring_passwd: "!s3cr3t"
opensearch_dashboards_user_passwd: "!s3cr3t"

# Size of the OpenSearch cluster
opensearch_replicas: 3

# Configuration properties thatr define the resource requirements of the OpenSearch pods
opensearch_resources_limits_memory: "4Gi"
opensearch_resources_limits_cpu: "2000m"

opensearch_resources_requests_memory: "2Gi"
opensearch_resources_requests_cpu: "1000m"

# Configures the size of the Persistent Volume Claim (PVC) for OpenSearch data storage
opensearch_pvc_size: "30Gi"
opensearch_storage_class: "longhorn"

# Whether to enable prometheus monitoring via plugin. Important, the exporter plugin must match OpenSearch's version.
opensearch_enable_monitoring: true

# If you have applied the corresponding taint to certain nodes in your cluster to
# repel general workloads and reserve those nodes for OpenSearch via
# `kubectl taint nodes <node-name> opensearch=true:NoSchedule`
opensearch_enable_node_tolerations: false

# Will taint the following k8s nodes with the key `opensearch=true:NoSchedule`
# if `opensearch_enable_node_tolerations` is set to true.
opensearch_nodes:
  - deskpi2
  - deskpi3
  - deskpi4

# This is the interval at which Prometheus will scrape metrics from OpenSearch.
opensearch_metrics_scrape_interval: "30s"

