# Default variables used by the route53-ddns role
---
# Enable AWS' `Route 53` DNS provider for routing public traffic to the cluster ingress.
enable_route53: false

# Whether to support IPv6 addresses
IPv6_enabled: true

# List of public sub-domains to register with the DNS (e.g. Route53)
public_domains: []

# Log file for the cron job that updates the Route 53 DNS records
cron_log_file: "/var/log/update_route53_ddns.log"

# When using the Route 53 DNS provider, replace with your AWS Access Key ID and Secret Access Key.
# Consider using Ansible Vault to store these variables securely.
aws_access_key_id:
aws_secret_access_key:
aws_region: us-east-1

# When using the Route 53 DNS provider, replace with your AWS Hosted Zone ID.
aws_hosted_zone_id:

# Your AWS account ID (e.g. "005162895111")
# Consider using Ansible Vault to store these variables securely.
aws_account_id:

# IAM username (e.g. "myuser" from `arn:aws:iam::<account-id>:user/myuser`)
# Consider using Ansible Vault to store these variables securely.
aws_iam_user: