# Ansible role defaults for Traefik Basic Auth
---
# Namespace to create the BasicAuth secret and middleware in.
basic_auth_namespace: default
# Name of the BasicAuth secret and middleware.
basic_auth_name:

# Credentials for the BasicAuth middleware
basic_auth_user: 'admin'
basic_auth_passwd: '!s3cr3t'