# Default variables used by the dns-server role.
---

# Name of the network interface dnsmasq should listen on (leave empty to infer from host)
dnsmasq_interface: ''
# IP address dnsmasq should listen on (leave empty to infer from host)
dnsmasq_listen_address: ''

# Path to the main configuration file
dnsmasq_conf_dir: '/etc/dnsmasq.d/'

# Top Level Domain
dns_domain: localnet
# Sub-Domain for the cluster
cluster_dns_domain: cluster.local

# Defines Cloudflare and Google public name servers as upstream name servers to dnsmasq
upstream_dns_servers:
  - 1.1.1.1
  - 8.8.8.8

# Additional DNS entries
# For Example:
# additional_dns_hosts:
#   ntp_server:
#     desc: "NTP Server"
#     hostname: ntp
#     ip: 10.0.0.1
#   dns_server:
#     desc: "DNS Server"
#     hostname: dns
#     ip: 10.0.0.1
additional_dns_hosts: {}

# DHCP range used by dnsmasq (should not overlap range of IP addresses used by MetalLB)
dhcp_range: ''
# Whether to enable the DHCP server in dnsmasq
enable_dhcp: false


