# Leverage the `nfs-subdir-external-provisioner` to create a storage class that can dynamically create a persistent volume.
#
# See: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
#
# In contrast to manually creating a persistent volume and persistent volume claim, this dynamic method cedes the lifecycle
# of the persistent volume over to the storage class itself.
#
# This can be used as an external storage for AlertManager and Prometheus, ensuring multi-node level durability (of the storage).
#
# This playbook drew its inspiration from: https://fabianlee.org/2022/01/12/kubernetes-nfs-mount-using-dynamic-volume-and-storage-class/
---
- name: Set up NFS Subdir External Provisioner
  hosts: control_plane

  gather_facts: true
  become: true

  environment:
    # The location of the kubeconfig file on the master node
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  vars:
    nfs_dir: /data/nfs1
    nfs_server:

  tasks:
    - name: Ensure prerequisite software packages are installed
      package:
        name:
          - nfs-common
          - nfs-kernel-server

    - name: Create the directory to share
      file:
        path: "{{ nfs_dir }}"
        state: directory
        owner: nobody
        group: nogroup
        mode: g+rwxs

    - name: Configure `/etc/exports` defining the share, and limiting access to clients in the cluster network.
      blockinfile:
        path: /etc/exports
        # This uses CIDR notation (e.g. 192.168.0.0/24) and assumes the subnet mask is 255.255.255.0 (i.e. '24' in CIDR Notation)
        block: "{{ nfs_dir + '\t' + ip_subnet_prefix + '.0/24' + '(rw,sync,no_subtree_check,no_root_squash)' }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Export NFS share"

    - name: Export all directories listed in `/etc/exports` for NFS
      shell:
        cmd: exportfs -a

    - name: Restart the NFS Kernel Server
      systemd:
        state: restarted
        name: nfs-kernel-server

    - name: Add the Kubernetes NFS Subdir External Provisioner chart repository.
      kubernetes.core.helm_repository:
        name: nfs-subdir-external-provisioner
        repo_url: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner"

    - name: Deploy the NFS Subdir External Provisioner chart.
      kubernetes.core.helm:
        name: nfs-subdir-external-provisioner
        chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
        namespace: default
        state: present
        values:
          nfs:
            server: "{{ ip_subnet_prefix + '.' + ip_octet | string }}"
            path: "{{ nfs_dir }}"
          storageClass:
            onDelete: delete