# Uninstalls Prometheus
#
# See https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#uninstall-helm-chart
---
- name: Uninstall Prometheus + Grafana monitoring stack.
  hosts: control_plane

  gather_facts: false
  become: true

  environment:
    # The location of the kubeconfig file on the master node
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  tasks:
    - name: Uninstall the kube-prometheus-stack.
      kubernetes.core.helm:
        name: cluster-monitoring
        namespace: default
        state: absent
        wait: true

    # CRDs created by this chart are not removed by default and should be manually cleaned up
    - name: Delete CRDs.
      kubernetes.core.k8s:
        api_version: v1
        kind: CustomResourceDefinition
        state: absent
        name: "{{ item }}"
      loop:
        - "alertmanagerconfigs.monitoring.coreos.com"
        - "alertmanagers.monitoring.coreos.com"
        - "podmonitors.monitoring.coreos.com"
        - "probes.monitoring.coreos.com"
        - "prometheuses.monitoring.coreos.com"
        - "prometheusrules.monitoring.coreos.com"
        - "servicemonitors.monitoring.coreos.com"
        - "thanosrulers.monitoring.coreos.com"