# Installs a Rook (https://rook.io/) operator and a Ceph (https://ceph.com/en/) storage cluster
---
- name: Install Rook-Ceph Storage Cluster
  hosts: control_plane

  gather_facts: true
  become: true

  vars:
    # See available releases: https://docs.ceph.com/en/latest/releases/
    ceph_version: v17.2.5
    # See available releases: https://hub.docker.com/r/rook/ceph/tags
    rook_ceph_version: v1.10.6
    rook_ceph_namespace: "rook-ceph"
    # The path on the host where configuration files will be persisted
    data_dir_host_path: /var/lib/rook

  environment:
    # The location of the kubeconfig file on the master node
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  tasks:

    # See https://rook.io/docs/rook/v1.10/Helm-Charts/operator-chart/
    - name: Add rook-release chart repo.
      kubernetes.core.helm_repository:
        name: rook-release
        repo_url: "https://charts.rook.io/release"

    - name: Deploy the Rook Storage Operator.
      kubernetes.core.helm:
        name: rook-ceph
        chart_ref: rook-release/rook-ceph
        namespace: "{{ rook_ceph_namespace }}"
        create_namespace: yes
        state: present
        values: "{{ lookup('template', './templates/ceph-operator-values.yaml') | from_yaml }}"
        wait: yes
        atomic: yes
        timeout: "10m0s"
      register: helm_result
      retries: 3
      delay: 60
      until: helm_result is succeeded

    # See https://rook.io/docs/rook/v1.10/Helm-Charts/ceph-cluster-chart/
    - name: Deploy the Ceph Storage Cluster.
      kubernetes.core.helm:
        name: rook-ceph-cluster
        chart_ref: rook-release/rook-ceph-cluster
        namespace: "{{ rook_ceph_namespace }}"
        create_namespace: yes
        state: present
        values: "{{ lookup('template', './templates/ceph-cluster-values.yaml') | from_yaml }}"
        wait: yes
        atomic: yes
        timeout: "10m0s"
      register: helm_result
      retries: 3
      delay: 60
      until: helm_result is succeeded
