{
 "title": "RPi Metrics",
 "description": "Hardware Telemetry from the DeskPis",
 "tags": [
  "Hardware",
  "Telemetry"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Currently Throttled",
   "type": "stat",
   "description": "Throttling can occur if the processor overheats or the power supply is inadequate. \n\nRaspberry Pi boards begin to throttle the processor when the temperature reaches 80°C, and throttle even further when it reaches the max temp of 85°C.",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpi_throttled_throttled{instance=\"192.168.30.10:9100\"}",
     "legendFormat": "deskpi 1 "
    },
    {
     "expr": "rpi_throttled_throttled{instance=\"192.168.30.11:9100\"}",
     "legendFormat": "deskpi 2"
    },
    {
     "expr": "rpi_throttled_throttled{instance=\"192.168.30.12:9100\"}",
     "legendFormat": "deskpi 3"
    },
    {
     "expr": "rpi_throttled_throttled{instance=\"192.168.30.13:9100\"}",
     "legendFormat": "deskpi 4"
    },
    {
     "expr": "rpi_throttled_throttled{instance=\"192.168.30.14:9100\"}",
     "legendFormat": "deskpi 5"
    },
    {
     "expr": "rpi_throttled_throttled{instance=\"192.168.30.15:9100\"}",
     "legendFormat": "deskpi 6"
    }
   ]
  },
  {
   "title": "Freq. Cap",
   "type": "stat",
   "description": "ARM frequency can be capped or throttled when the system's power supply is inadequate, it overheats, or it hits a configured maximum clock speed",
   "gridPos": { "h": 10, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpi_throttled_freq_capped{instance=\"192.168.30.10:9100\"}",
     "legendFormat": "deskpi 1 "
    },
    {
     "expr": "rpi_throttled_freq_capped{instance=\"192.168.30.11:9100\"}",
     "legendFormat": "deskpi 2"
    },
    {
     "expr": "rpi_throttled_freq_capped{instance=\"192.168.30.12:9100\"}",
     "legendFormat": "deskpi 3"
    },
    {
     "expr": "rpi_throttled_freq_capped{instance=\"192.168.30.13:9100\"}",
     "legendFormat": "deskpi 4"
    },
    {
     "expr": "rpi_throttled_freq_capped{instance=\"192.168.30.14:9100\"}",
     "legendFormat": "deskpi 5"
    },
    {
     "expr": "rpi_throttled_freq_capped{instance=\"192.168.30.15:9100\"}",
     "legendFormat": "deskpi 6"
    }
   ]
  },
  {
   "title": "Soft Temp. Limit Active",
   "type": "stat",
   "description": "Reached a temperature that triggers a performance reduction, but not an emergency shutdown.\n\nRaspberry Pi boards begin to throttle the processor when the temperature reaches 80°C, and throttle even further when it reaches the max temp of 85°C.",
   "gridPos": { "h": 10, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpi_throttled_soft_temp{instance=\"192.168.30.10:9100\"}",
     "legendFormat": "deskpi 1 "
    },
    {
     "expr": "rpi_throttled_soft_temp{instance=\"192.168.30.11:9100\"}",
     "legendFormat": "deskpi 2"
    },
    {
     "expr": "rpi_throttled_soft_temp{instance=\"192.168.30.12:9100\"}",
     "legendFormat": "deskpi 3"
    },
    {
     "expr": "rpi_throttled_soft_temp{instance=\"192.168.30.13:9100\"}",
     "legendFormat": "deskpi 4"
    },
    {
     "expr": "rpi_throttled_soft_temp{instance=\"192.168.30.14:9100\"}",
     "legendFormat": "deskpi 5"
    },
    {
     "expr": "rpi_throttled_soft_temp{instance=\"192.168.30.15:9100\"}",
     "legendFormat": "deskpi 6"
    }
   ]
  },
  {
   "title": "Undervoltage Detected",
   "type": "stat",
   "description": "Power supply inadequate.",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpi_throttled_undervoltage{instance=\"192.168.30.10:9100\"}",
     "legendFormat": "deskpi 1 "
    },
    {
     "expr": "rpi_throttled_undervoltage{instance=\"192.168.30.11:9100\"}",
     "legendFormat": "deskpi 2"
    },
    {
     "expr": "rpi_throttled_undervoltage{instance=\"192.168.30.12:9100\"}",
     "legendFormat": "deskpi 3"
    },
    {
     "expr": "rpi_throttled_undervoltage{instance=\"192.168.30.13:9100\"}",
     "legendFormat": "deskpi 4"
    },
    {
     "expr": "rpi_throttled_undervoltage{instance=\"192.168.30.14:9100\"}",
     "legendFormat": "deskpi 5"
    },
    {
     "expr": "rpi_throttled_undervoltage{instance=\"192.168.30.15:9100\"}",
     "legendFormat": "deskpi 6"
    }
   ]
  },
  {
   "title": "Undervoltage Occurrences",
   "type": "table",
   "description": "Undervoltage event history.",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time(rpi_throttled_undervoltage_occurred{instance=\"192.168.30.10:9100\"}[24h])",
     "legendFormat": "deskpi 1"
    },
    {
     "expr": "max_over_time(rpi_throttled_undervoltage_occurred{instance=\"192.168.30.11:9100\"}[24h])",
     "legendFormat": "deskpi 2"
    },
    {
     "expr": "max_over_time(rpi_throttled_undervoltage_occurred{instance=\"192.168.30.12:9100\"}[24h])",
     "legendFormat": "deskpi 3"
    },
    {
     "expr": "max_over_time(rpi_throttled_undervoltage_occurred{instance=\"192.168.30.13:9100\"}[24h])",
     "legendFormat": "deskpi 4"
    },
    {
     "expr": "max_over_time(rpi_throttled_undervoltage_occurred{instance=\"192.168.30.14:9100\"}[24h])",
     "legendFormat": "deskpi 5"
    },
    {
     "expr": "max_over_time(rpi_throttled_undervoltage_occurred{instance=\"192.168.30.15:9100\"}[24h])",
     "legendFormat": "deskpi 6"
    }
   ]
  },
  {
   "title": "Soft Temp. Limit Occurrences",
   "type": "table",
   "description": "History of \"Soft Temperature\" limit activations.",
   "gridPos": { "h": 10, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time(rpi_throttled_soft_temp_occurred{instance=\"192.168.30.10:9100\"}[24h])",
     "legendFormat": "deskpi 1"
    },
    {
     "expr": "max_over_time(rpi_throttled_soft_temp_occurred{instance=\"192.168.30.11:9100\"}[24h])",
     "legendFormat": "deskpi 2"
    },
    {
     "expr": "max_over_time(rpi_throttled_soft_temp_occurred{instance=\"192.168.30.12:9100\"}[24h])",
     "legendFormat": "deskpi 3"
    },
    {
     "expr": "max_over_time(rpi_throttled_soft_temp_occurred{instance=\"192.168.30.13:9100\"}[24h])",
     "legendFormat": "deskpi 4"
    },
    {
     "expr": "max_over_time(rpi_throttled_soft_temp_occurred{instance=\"192.168.30.14:9100\"}[24h])",
     "legendFormat": "deskpi 5"
    },
    {
     "expr": "max_over_time(rpi_throttled_soft_temp_occurred{instance=\"192.168.30.15:9100\"}[24h])",
     "legendFormat": "deskpi 6"
    }
   ]
  },
  {
   "title": "Freq. Cap Occurrences",
   "type": "table",
   "description": "History of frequency cap events",
   "gridPos": { "h": 10, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time(rpi_throttled_freq_capped_occurred{instance=\"192.168.30.10:9100\"}[24h])",
     "legendFormat": "deskpi 1"
    },
    {
     "expr": "max_over_time(rpi_throttled_freq_capped_occurred{instance=\"192.168.30.11:9100\"}[24h])",
     "legendFormat": "deskpi 2"
    },
    {
     "expr": "max_over_time(rpi_throttled_freq_capped_occurred{instance=\"192.168.30.12:9100\"}[24h])",
     "legendFormat": "deskpi 3"
    },
    {
     "expr": "max_over_time(rpi_throttled_freq_capped_occurred{instance=\"192.168.30.13:9100\"}[24h])",
     "legendFormat": "deskpi 4"
    },
    {
     "expr": "max_over_time(rpi_throttled_freq_capped_occurred{instance=\"192.168.30.14:9100\"}[24h])",
     "legendFormat": "deskpi 5"
    },
    {
     "expr": "max_over_time(rpi_throttled_freq_capped_occurred{instance=\"192.168.30.15:9100\"}[24h])",
     "legendFormat": "deskpi 6"
    }
   ]
  },
  {
   "title": "Throttling Occurrences",
   "type": "table",
   "description": "History of throttling events.",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time(rpi_throttled_throttled_occurred{instance=\"192.168.30.10:9100\"}[24h])",
     "legendFormat": "deskpi 1"
    },
    {
     "expr": "max_over_time(rpi_throttled_throttled_occurred{instance=\"192.168.30.11:9100\"}[24h])",
     "legendFormat": "deskpi 2"
    },
    {
     "expr": "max_over_time(rpi_throttled_throttled_occurred{instance=\"192.168.30.12:9100\"}[24h])",
     "legendFormat": "deskpi 3"
    },
    {
     "expr": "max_over_time(rpi_throttled_throttled_occurred{instance=\"192.168.30.13:9100\"}[24h])",
     "legendFormat": "deskpi 4"
    },
    {
     "expr": "max_over_time(rpi_throttled_throttled_occurred{instance=\"192.168.30.14:9100\"}[24h])",
     "legendFormat": "deskpi 5"
    },
    {
     "expr": "max_over_time(rpi_throttled_throttled_occurred{instance=\"192.168.30.15:9100\"}[24h])",
     "legendFormat": "deskpi 6"
    }
   ]
  },
  {
   "title": "CPU Temps.",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpi_cpu_temperature_celsius{instance=\"192.168.30.10:9100\"}",
     "legendFormat": "DeskPi 1"
    },
    {
     "expr": "rpi_cpu_temperature_celsius{instance=\"192.168.30.11:9100\"}",
     "legendFormat": "DeskPi 2"
    },
    {
     "expr": "rpi_cpu_temperature_celsius{instance=\"192.168.30.12:9100\"}",
     "legendFormat": "DeskPi 3"
    },
    {
     "expr": "rpi_cpu_temperature_celsius{instance=\"192.168.30.13:9100\"}",
     "legendFormat": "DeskPi 4"
    },
    {
     "expr": "rpi_cpu_temperature_celsius{instance=\"192.168.30.14:9100\"}",
     "legendFormat": "DeskPi 5"
    },
    {
     "expr": "rpi_cpu_temperature_celsius{instance=\"192.168.30.15:9100\"}",
     "legendFormat": "DeskPi 6"
    }
   ]
  },
  {
   "title": "CPU Temps.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "rpi_cpu_temperature_celsius{instance=\"192.168.30.10:9100\"}",
     "legendFormat": "deskpi1"
    },
    {
     "expr": "rpi_cpu_temperature_celsius{instance=\"192.168.30.11:9100\"}",
     "legendFormat": "deskpi2"
    },
    {
     "expr": "rpi_cpu_temperature_celsius{instance=\"192.168.30.12:9100\"}",
     "legendFormat": "deskpi3"
    },
    {
     "expr": "rpi_cpu_temperature_celsius{instance=\"192.168.30.13:9100\"}",
     "legendFormat": "deskpi4"
    },
    {
     "expr": "rpi_cpu_temperature_celsius{instance=\"192.168.30.14:9100\"}",
     "legendFormat": "deskpi5"
    },
    {
     "expr": "rpi_cpu_temperature_celsius{instance=\"192.168.30.15:9100\"}",
     "legendFormat": "deskpi6"
    },
    {}
   ]
  },
  {
   "title": "GPU Temps.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "rpi_gpu_temperature_celsius{instance=\"192.168.30.10:9100\"}",
     "legendFormat": "deskpi 1"
    },
    {
     "expr": "rpi_gpu_temperature_celsius{instance=\"192.168.30.11:9100\"}",
     "legendFormat": "deskpi 2"
    },
    {
     "expr": "rpi_gpu_temperature_celsius{instance=\"192.168.30.12:9100\"}",
     "legendFormat": "deskpi 3"
    },
    {
     "expr": "rpi_gpu_temperature_celsius{instance=\"192.168.30.13:9100\"}",
     "legendFormat": "deskpi 4"
    },
    {
     "expr": "rpi_gpu_temperature_celsius{instance=\"192.168.30.14:9100\"}",
     "legendFormat": "deskpi 5"
    },
    {
     "expr": "rpi_gpu_temperature_celsius{instance=\"192.168.30.15:9100\"}",
     "legendFormat": "deskpi 6"
    }
   ]
  },
  {
   "title": "CPU Clocks",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpi_cpu_clock_hz{instance=\"192.168.30.10:9100\"}",
     "legendFormat": "DeskPi 1"
    },
    {
     "expr": "rpi_cpu_clock_hz{instance=\"192.168.30.11:9100\"}",
     "legendFormat": "DeskPi 2"
    },
    {
     "expr": "rpi_cpu_clock_hz{instance=\"192.168.30.12:9100\"}",
     "legendFormat": "DeskPi 3"
    },
    {
     "expr": "rpi_cpu_clock_hz{instance=\"192.168.30.13:9100\"}",
     "legendFormat": "DeskPi 4"
    },
    {
     "expr": "rpi_cpu_clock_hz{instance=\"192.168.30.14:9100\"}",
     "legendFormat": "DeskPi 5"
    },
    {
     "expr": "rpi_cpu_clock_hz{instance=\"192.168.30.15:9100\"}",
     "legendFormat": "DeskPi 6"
    }
   ]
  },
  {
   "title": "CPU Clocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "rpi_cpu_clock_hz{instance=\"192.168.30.10:9100\"}",
     "legendFormat": "deskpi 1"
    },
    {
     "expr": "rpi_cpu_clock_hz{instance=\"192.168.30.11:9100\"}",
     "legendFormat": "deskpi 2"
    },
    {
     "expr": "rpi_cpu_clock_hz{instance=\"192.168.30.12:9100\"}",
     "legendFormat": "deskpi 3"
    },
    {
     "expr": "rpi_cpu_clock_hz{instance=\"192.168.30.13:9100\"}",
     "legendFormat": "deskpi 4"
    },
    {
     "expr": "rpi_cpu_clock_hz{instance=\"192.168.30.14:9100\"}",
     "legendFormat": "deskpi 5"
    },
    {
     "expr": "rpi_cpu_clock_hz{instance=\"192.168.30.15:9100\"}",
     "legendFormat": "deskpi 6"
    }
   ]
  },
  {
   "title": "GPU Clocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "rpi_gpu_clock_hz{instance=\"192.168.30.10:9100\"}",
     "legendFormat": "deskpi 1"
    },
    {
     "expr": "rpi_gpu_clock_hz{instance=\"192.168.30.11:9100\"}",
     "legendFormat": "deskpi 2"
    },
    {
     "expr": "rpi_gpu_clock_hz{instance=\"192.168.30.12:9100\"}",
     "legendFormat": "deskpi 3"
    },
    {
     "expr": "rpi_gpu_clock_hz{instance=\"192.168.30.13:9100\"}",
     "legendFormat": "deskpi 4"
    },
    {
     "expr": "rpi_gpu_clock_hz{instance=\"192.168.30.14:9100\"}",
     "legendFormat": "deskpi 5"
    },
    {
     "expr": "rpi_gpu_clock_hz{instance=\"192.168.30.15:9100\"}",
     "legendFormat": "deskpi 6"
    }
   ]
  },
  {
   "title": "Memory (Available)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpi_memory_avail_bytes{instance=\"192.168.30.10:9100\"}",
     "legendFormat": "DeskPi 1"
    },
    {
     "expr": "rpi_memory_avail_bytes{instance=\"192.168.30.11:9100\"}",
     "legendFormat": "DeskPi 2"
    },
    {
     "expr": "rpi_memory_avail_bytes{instance=\"192.168.30.12:9100\"}",
     "legendFormat": "DeskPi 3"
    },
    {
     "expr": "rpi_memory_avail_bytes{instance=\"192.168.30.13:9100\"}",
     "legendFormat": "DeskPi 4"
    },
    {
     "expr": "rpi_memory_avail_bytes{instance=\"192.168.30.14:9100\"}",
     "legendFormat": "DeskPi 5"
    },
    {
     "expr": "rpi_memory_avail_bytes{instance=\"192.168.30.15:9100\"}",
     "legendFormat": "DeskPi 6"
    }
   ]
  },
  {
   "title": "Memory (Available)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rpi_memory_avail_bytes{instance=\"192.168.30.10:9100\"}",
     "legendFormat": "deskpi 1"
    },
    {
     "expr": "rpi_memory_avail_bytes{instance=\"192.168.30.11:9100\"}",
     "legendFormat": "deskpi 2"
    },
    {
     "expr": "rpi_memory_avail_bytes{instance=\"192.168.30.12:9100\"}",
     "legendFormat": "deskpi 3"
    },
    {
     "expr": "rpi_memory_avail_bytes{instance=\"192.168.30.13:9100\"}",
     "legendFormat": "deskpi 4"
    },
    {
     "expr": "rpi_memory_avail_bytes{instance=\"192.168.30.14:9100\"}",
     "legendFormat": "deskpi 5"
    },
    {
     "expr": "rpi_memory_avail_bytes{instance=\"192.168.30.15:9100\"}",
     "legendFormat": "deskpi 6"
    }
   ]
  },
  {
   "title": "Memory (Free)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rpi_memory_free_bytes{instance=\"192.168.30.10:9100\"}",
     "legendFormat": "deskpi 1"
    },
    {
     "expr": "rpi_memory_free_bytes{instance=\"192.168.30.11:9100\"}",
     "legendFormat": "deskpi 2"
    },
    {
     "expr": "rpi_memory_free_bytes{instance=\"192.168.30.12:9100\"}",
     "legendFormat": "deskpi 3"
    },
    {
     "expr": "rpi_memory_free_bytes{instance=\"192.168.30.13:9100\"}",
     "legendFormat": "deskpi 4"
    },
    {
     "expr": "rpi_memory_free_bytes{instance=\"192.168.30.14:9100\"}",
     "legendFormat": "deskpi 5"
    },
    {
     "expr": "rpi_memory_free_bytes{instance=\"192.168.30.15:9100\"}",
     "legendFormat": "deskpi 6"
    }
   ]
  }
 ]
}