# Tasks to uninstall the Linkerd Viz & Control Plane (see https://linkerd.io/2.12/tasks/uninstall/)
---
- name: Check if Linkerd CLI is available
  ansible.builtin.stat:
    path: "{{ linkerd_bin }}"
  register: linkerd_cli

- name: Remove Linkerd Viz
  shell: >
     linkerd viz uninstall | kubectl delete -f -
  when: linkerd_cli.stat.exists

- name: Remove Linkerd Control Plane
  shell: >
     linkerd uninstall | kubectl delete -f -
  when: linkerd_cli.stat.exists

- name: Uninstall Linkerd Control Plane with Helm
  kubernetes.core.helm:
    name: linkerd-control-plane
    namespace: "{{ k3s_linkerd_namespace }}"
    state: absent
    wait: true

- name: Remove the Linkerd namespace
  kubernetes.core.k8s:
    api_version: v1
    name: "{{ k3s_linkerd_namespace }}"
    kind: Namespace
    state: absent
