# Tasks for the removal of Traefik
---
- name: Get a list of all Ingress
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Ingress
  register: ingress

- name: Delete all Ingress
  kubernetes.core.k8s:
    api_version: v1
    kind: Ingress
    state: absent
    name: "{{ item }}"
  loop: "{{ ingress| json_query('resources[*].metadata.name') }}"
  ignore_errors: true

- name: Get a list of all Ingress Routes
  kubernetes.core.k8s_info:
    api_version: "traefik.io/v1alpha1"
    kind: IngressRoute
  register: ingress_routes

- name: Delete Ingress Routes
  kubernetes.core.k8s:
    api_version: "traefik.io/v1alpha1"
    kind: IngressRoute
    state: absent
    name: "{{ item }}"
  loop: "{{ ingress_routes | json_query('resources[*].metadata.name') }}"
  ignore_errors: true

- name: Get a list of all Middleware
  kubernetes.core.k8s_info:
    api_version: "traefik.io/v1alpha1"
    kind: Middleware
  register: middle_wares

- name: Delete Middleware
  kubernetes.core.k8s:
    api_version: "traefik.io/v1alpha1"
    kind: Middleware
    state: absent
    name: "{{ item }}"
  loop: "{{ middle_wares | json_query('resources[*].metadata.name') }}"
  ignore_errors: true

# Delete any Service Monitors
- name: Get a list of Traefik Service Monitors
  kubernetes.core.k8s_info:
    api_version: "monitoring.coreos.com/v1"
    kind: ServiceMonitor
    label_selectors:
      - app = traefik
  register: service_monitors

- name: Delete Traefik Service Monitors
  kubernetes.core.k8s:
    api_version: "monitoring.coreos.com/v1"
    kind: ServiceMonitor
    state: absent
    name: "{{ item }}"
  loop: "{{ service_monitors | json_query('resources[*].metadata.name') }}"
  ignore_errors: true

- name: Get a list of all Secrets
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    namespace: "{{ k3s_traefik_namespace }}"
  register: secrets

- name: Delete Secrets
  kubernetes.core.k8s:
    api_version: v1
    kind: Secret
    namespace: "{{ k3s_traefik_namespace }}"
    state: absent
    name: "{{ item }}"
  loop: "{{ secrets | json_query('resources[*].metadata.name') }}"
  ignore_errors: true

- name: Get a list of all ConfigMaps
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    namespace: "{{ k3s_traefik_namespace }}"
  register: configmaps

- name: Delete ConfigMaps
  kubernetes.core.k8s:
    api_version: v1
    kind: ConfigMap
    namespace: "{{ k3s_traefik_namespace }}"
    state: absent
    name: "{{ item }}"
  loop: "{{ configmaps | json_query('resources[*].metadata.name') }}"
  ignore_errors: true

- name: Uninstall Traefik with Helm
  kubernetes.core.helm:
    name: traefik
    namespace: "{{ k3s_traefik_namespace }}"
    state: absent
    wait: true

- name: Remove the Traefik namespace
  kubernetes.core.k8s:
    api_version: v1
    name: "{{ k3s_traefik_namespace }}"
    kind: Namespace
    state: absent




