# Default variables used by the Cluster Preparation role
---
# Whether Ubuntu was installed as the OS on the Desk Pi
ubuntu_os: false
# Whether to format the available SD card to ext4
format_sdcard: false
# Whether to reduce the memory allocated to the GPU
reduce_gpu_mem: true
# This tells the firmware of the CM5 “I know my PSU can handle it, skip your safety limit.”
disable_cm5_pd_current_limit: false

# In Ubuntu cmdline.txt and config.txt is located in a different location to Raspberry Pi OS
cmdline_txt_path: "{{ '/boot/firmware/cmdline.txt' if ubuntu_os else '/boot/cmdline.txt' }}"
config_txt_path: "{{ '/boot/firmware/config.txt' if ubuntu_os else '/boot/config.txt' }}"

# Software packages to install
software_packages:
  - python3-pip
  - python3-setuptools
  - build-essential
  - iptables
  - net-tools
  - netcat-openbsd
  - golang
  - git
  - podman
  - lvm2
  - nfs-common
  - fake-hwclock
  - raspi-config
  - ntpsec-ntpdate
  - jq
  - yq
  - gawk

# Specific software packages required for Ubuntu installations
software_packages_ubuntu:
  - libraspberrypi-bin
  - linux-raspi
  #- linux-modules-extra-raspi # This package was merged into linux-raspi since Ubuntu >=24.4

# Python libraries to install
python_libs:
  - pyyaml
  - kubernetes
  - kubernetes-validate
  - passlib