# Playbook for installing various additional packages to k3s
#
# These include
# - MetalLB (Load Balancer)
# - Cert-Manager (Certificate Management)
# - Linkerd (Service Mesh)
# - Traefik (Ingress Controller)
# = Longhorn (Storage Controller)
#
# Packages are tagged and can be played individually via the `--tags` argument for `ansible-playbook`
#
# Assumes 'k3s-install.yml' and 'k3s-post-install.yml' was run previously.
---
- name: Install various packages to k3s (affects all hosts in the cluster)
  hosts: cluster

  gather_facts: false # Do not gather facts here, as we will do it in the pre_tasks
  become: true

  vars_files:
    - vars/config.yml

  environment:
    K8S_AUTH_KUBECONFIG: /home/{{ ansible_user }}/.kube/config

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
      tags: ["always"]

    - name: Include vault variables
      include_vars: "vars/vault.yml"
      tags: ["always"]

  roles:
    - role: longhorn-install/cluster-prep
      tags: ['longhorn']
      when: k3s_enable_block_storage

    - role: rpi-metrics-exporter-install
      tags: ['rpi-metrics', 'monitoring']
      when: k3s_enable_monitoring and k3s_enable_rpi_metrics_exporter

- name: Install various packages to k3s (via the control plane).
  hosts: control_plane

  gather_facts: false # Do not gather facts here, as we will do it in the pre_tasks
  become: true

  collections:
    - kubernetes.core

  vars_files:
    - vars/config.yml

  environment:
    K8S_AUTH_KUBECONFIG: /home/{{ ansible_user }}/.kube/config

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
      tags: ["always"]

    - name: Include vault variables
      include_vars: "vars/vault.yml"
      tags: ['always']

    - name: Ensure Helm Diff Plugin is installed
      kubernetes.core.helm_plugin:
        plugin_path: https://github.com/databus23/helm-diff
        state: present
      tags: ['always']

  roles:
    - role: metallb-install
      tags: ['metallb']

    - role: route53-ddns-install
      tags: ['certmanager', 'route53ddns']
      when: k3s_enable_route53_ddns

    - role: cert-manager-install
      tags: ['certmanager']

    - role: linkerd-install
      tags: ['linkerd']
      when: k3s_enable_service_mesh

    - role: traefik-install
      tags: ['traefik']

    - role: longhorn-install/control-plane
      tags: ['longhorn']
      when: k3s_enable_block_storage

    - role: prometheus-install
      tags: ['prometheus', 'monitoring']
      when: k3s_enable_monitoring

    - role: prometheus-post-install
      tags: ['prometheus-post', 'monitoring']
      when: k3s_enable_monitoring

    - role: opensearch-install
      tags: ['opensearch', 'logstack']
      when: k3s_enable_logstack

    - role: opensearch-dashboards-install
      tags: ['opensearch-dashboards', 'logstack']
      when: k3s_enable_logstack

    - role: fluentbit-install
      tags: ['fluentbit', 'logstack']
      when: k3s_enable_logstack
