# Playbook for preparing the DeskPi Super6c cluster
#
# Invokes the roles
# - cluster-prep
# - ricsanfre.ntp (see https://galaxy.ansible.com/ricsanfre/ntp)
# - dnsmasq
---
- name: Prepare control plane
  hosts: control_plane

  gather_facts: true
  become: true

  vars_files:
    - vars/config.yml

  vars:
    ntp_allow_hosts:
      - "{{ ip_subnet_prefix }}.0/24"

  roles:
    # Cluster Preparation
    - role: cluster-prep
      tags: [prep]

    # NTP Server Configuration
    - role: chrony
      tags: [ntp, chrony]

    # DNS Server Configuration
    - role: dnsmasq
      tags: [dns, dnsmasq]


- name: Prepare the cluster
  hosts: nodes

  gather_facts: false
  become: true

  vars_files:
    - vars/config.yml

  vars:
    ntp_servers:
      - server: "{{ ntp_server }}"
        type: server

  roles:
    # Cluster Preparation
    - role: cluster-prep
      tags: [prep]

    # NTP Client Configuration
    - role: chrony
      tags: [ntp, chrony]