# Playbook for preparing the DeskPi Super6c cluster
#
# Invokes the roles
# - cluster-prep (Cluster Preparation)
# - chrony (NTP Server/Client)
# - dnsmasq (DNS Server)
---
- name: Prepare control plane
  hosts: control_plane

  gather_facts: true
  become: true

  vars_files:
    - vars/config.yml

  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yml"
      tags: ["always"]

  vars:
    ntp_allow_hosts:
      - "{{ ip_subnet_prefix }}.0/24"

  roles:
    # NTP Server Configuration
    - role: chrony
      tags: ['ntp', 'chrony']

    # DNS Server Configuration
    - role: dnsmasq
      tags: ['dns', 'dnsmasq']

    # Cluster Preparation
    - role: cluster-prep
      tags: ['prep']

- name: Prepare the cluster
  hosts: nodes

  gather_facts: false
  become: true

  vars_files:
    - vars/config.yml

  vars:
    ntp_servers:
      - server: "{{ ntp_server }}"
        type: server

  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yml"
      tags: ["always"]

  roles:
    # NTP Client Configuration
    - role: chrony
      tags: ['ntp', 'chrony']

    # Cluster Preparation
    - role: cluster-prep
      tags: ['prep']