# Playbook for certain operations after installing k3s on the DeskPi Super6c cluster:
#
# - Sets up kubectl autocompletion
# - Sets up HELM
# - Creates an NFS export and NFS Storage Class on the Control Plane.
# - Runs the post-install role for any additional tasks that may be needed after k3s installation.
#
# Assumes 'k3s-install.yml' was run previously.
---
# Enables kubectl autocompletion and the alias 'kc'.
#
# See https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/#enable-kubectl-autocompletion
- name: Enable kubectl autocompletion
  hosts: cluster

  gather_facts: false
  become: true

  tasks:
    - name: Source kubectl completion script
      blockinfile:
        path: /home/{{ ansible_user }}/.bashrc
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Source Kubectl Autocompletion"
        block: |
          source <(kubectl completion bash)
          alias kc='kubectl'
          complete -o default -F __start_kubectl kc

- name: Operations after k3s cluster installation.
  hosts: control_plane

  gather_facts: true
  become: true

  collections:
    - kubernetes.core

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  vars_files:
    - vars/config.yml

  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yml"
      tags: ["always"]

    # Install kubernetes core collection dependencies (kubernetes python package) using PIP.
    - name: Ensure PIP is installed.
      package:
        name:
          - python3-pip
          - python3-setuptools
        state: present
      become: true
      tags: ['always']

    - name: Ensure kubernetes Python library is installed.
      pip:
        name: kubernetes
        state: present
        break_system_packages: yes # Allow pip to modify an externally-managed Python installation as defined by PEP 668
      become: true
      tags: ['always']

  roles:
    - role: helm
      tags: ['helm']
    - role: nfs-storage
      tags: ['nfs']
    - role: cluster-post-install
      tags: ['post']
