# Playbook for uninstalling various packages from k3s
#
# These include
# - Cert Manager
# - Traefik
# - MetalLB
# - Longhorn
#
# Packages are tagged and can be played individually via the `--tags` argument for `ansible-playbook`
#
# Assumes 'k3s-install.yml' and 'k3s-post-install.yml' were run previously.
---
- name: Remove packages from k3s.
  hosts: control_plane

  gather_facts: true
  become: true

  vars_files:
    - vars/config.yml

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yml"
      tags: ["always"]

  roles:
    - role: opensearch-uninstall
      tags: ['opensearch', 'logstack']
      when: k3s_enable_logstack

    - role: prometheus-uninstall
      tags: ['prometheus']
      when: k3s_enable_monitoring

    - role: longhorn-uninstall
      tags: ['longhorn']
      when: k3s_enable_block_storage

    - role: traefik-uninstall
      tags: ['traefik']

    - role: linkerd-uninstall
      tags: ['linkerd']
      when: k3s_enable_service_mesh

    - role: cert-manager-uninstall
      tags: ['certmanager']

    - role: route53-ddns-uninstall
      tags: ['certmanager', 'route53ddns']

    - role: metallb-uninstall
      tags: ['metallb']