# Playbook for installing various additional packages to k3s
#
# These include
# - Prometheus & Grafana
# - Cert Manager
# - Rook & Ceph
#
# Packages are tagged and can be played individually via the `--tags` argument for `ansible-playbook`
#
# Assumes 'k3s-install.yml' and 'k3s-post-install.yml' was run previously.
---
- name: Remove packages from k3s.
  hosts: control_plane

  gather_facts: true
  become: true

  vars_files:
    - vars/config.yml

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  roles:
    - role: longhorn-uninstall
      tags: ['longhorn']
      when: k3s_enable_block_storage | bool

    - role: traefik-uninstall
      tags: ['traefik']

    - role: linkerd-uninstall
      tags: ['linkerd']
      when: k3s_enable_service_mesh | bool

    - role: cert-manager-uninstall
      tags: ['certmanager']

    - role: metallb-uninstall
      tags: ['metallb']