# Removes all packages installed with Snap
---
- name: Remove all Snap Packages. Will retry at least 3 times.
  block:
    - name: Increment the retry count
      set_fact:
        retry_count: "{{ 0 if retry_count is undefined else retry_count | int + 1 }}"

    - name: List snap packages
      ansible.builtin.shell: |
        for i in `snap list | awk '!/Name/{print $1}'`;
        do echo $i;
        done
      changed_when: false
      register: snap_packages

    - name: Remove snap packages (this might fail - will retry)
      ansible.builtin.command: snap remove {{ item }}
      register: snap_remove_output
      with_items: "{{ snap_packages.stdout_lines }}"
  rescue:
    - name: Check number of retries and fail if greater than 3
      fail:
        msg: "Removal of snap packages failed, maximum number retries reached."
      when: retry_count | int == 3

    - name: Print retry message
      debug:
        msg: "Removing snap package failed, retrying..."
    - name: retrying deletion
      include_tasks: remove_snap_packages.yml